### ISSUE TITLE
Implement: epicurve to EpiNow2

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/data_pipelines#7]
- highlight differences from EpiEstim
 - get EpiNow2 results stratified by group
- custom graph to show results
- summary table + export

**Comment by Bisaloo** [comment]
EpiNow2 doesn't work well out of the box with incidence2 objects because it doesn't like the `grates_yearweek` class that the `date` column might use.

**Comment by Bisaloo** [comment]
Done in #31.
